runtime: python310
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  # URL-ul serviciului de stoc; acesta se va folosi în backend pentru a face apeluri.
  STOCK_SERVICE_URL: "https://stock-dot-cc-team-456211.appspot.com"