runtime: python310
entrypoint: gunicorn -b :$PORT main:app
env_variables:
  SALE_SERVICE_URL: "https://sale-dot-cc-team-456211.appspot.com"
  APPOINTMENT_SERVICE_URL: "https://appointment-dot-cc-team-456211.appspot.com"
  STOCK_SERVICE_URL: "https://stock-dot-cc-team-456211.appspot.com"
